# Generated by Django 6.1 on 2026-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='responsable_cni/', verbose_name="Carte d'identité (CNI) - Verso"),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='responsable_cni/', verbose_name="Carte d'identité (CNI) - Recto"),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Coché une fois que le responsable a renseigné les informations de sa structure (nom, adresse, justificatif, CNI).', verbose_name="Profil de l'orphelinat complété"),
        ),
    ]
