# Generated by Django 6.1 on 2026-08-09 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_id_card_back_user_id_card_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='organization_owner',
            field=models.ForeignKey(blank=True, help_text="Si renseigné, ce compte gère l'orphelinat de ce responsable principal en tant que membre d'équipe.", limit_choices_to={'role': 'responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name="Responsable principal de l'orphelinat"),
        ),
        migrations.CreateModel(
            name='TeamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de la personne invitée')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False, verbose_name='Utilisée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('organization_owner', models.ForeignKey(limit_choices_to={'role': 'responsable'}, on_delete=django.db.models.deletion.CASCADE, related_name='team_invites', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
            ],
            options={
                'verbose_name': "Invitation d'équipe",
                'verbose_name_plural': "Invitations d'équipe",
                'ordering': ['-created_at'],
            },
        ),
    ]
