# Generated by Django 6.1 on 2026-08-09 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom')),
                ('icon', models.CharField(default='tag', help_text="Nom de l'icône Lucide utilisée dans l'interface (ex: heart-pulse).", max_length=50, verbose_name='Icône (Lucide)')),
            ],
            options={
                'verbose_name': 'Catégorie de besoin',
                'verbose_name_plural': 'Catégories de besoins',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du besoin')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('children_count', models.PositiveIntegerField(default=0, verbose_name="Nombre d'enfants concernés")),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant cible (FCFA)')),
                ('collected_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Montant collecté (FCFA)')),
                ('is_closed', models.BooleanField(default=False, help_text="Coché lorsque l'orphelinat a confirmé la réception effective du don sur le terrain.", verbose_name='Besoin clôturé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='needs', to='donations.category', verbose_name='Catégorie')),
                ('orphanage', models.ForeignKey(limit_choices_to={'role': 'responsable'}, on_delete=django.db.models.deletion.CASCADE, related_name='needs', to=settings.AUTH_USER_MODEL, verbose_name='Orphelinat')),
            ],
            options={
                'verbose_name': 'Besoin',
                'verbose_name_plural': 'Besoins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=30, unique=True, verbose_name='Référence')),
                ('donation_type', models.CharField(choices=[('financier', 'Don Financier'), ('nature', 'Don en Nature')], default='financier', max_length=20, verbose_name='Type de don')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Montant (FCFA)')),
                ('item_description', models.CharField(blank=True, max_length=255, verbose_name='Description des articles (don en nature)')),
                ('message', models.TextField(blank=True, verbose_name='Message du donateur')),
                ('status', models.CharField(choices=[('en_attente', 'En attente de réception'), ('receptionne', 'Réceptionné & Confirmé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du don')),
                ('donateur', models.ForeignKey(limit_choices_to={'role': 'donateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL, verbose_name='Donateur')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donations.need', verbose_name='Besoin concerné')),
            ],
            options={
                'verbose_name': 'Don',
                'verbose_name_plural': 'Dons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Titre')),
                ('message', models.CharField(max_length=255, verbose_name='Message')),
                ('level', models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement')], default='info', max_length=20, verbose_name='Niveau')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Lien associé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de réception')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
