# Generated by Django 6.1 on 2026-08-09 15:00

from django.db import migrations

DEFAULT_CATEGORIES = [
    ("Santé & Médicaments", "heart-pulse"),
    ("Nutrition & Alimentation", "utensils"),
    ("Éducation & Scolarité", "graduation-cap"),
    ("Hygiène & Vêtements", "shirt"),
    ("Infrastructure & Logement", "home"),
]


def create_categories(apps, schema_editor):
    Category = apps.get_model('donations', 'Category')
    for name, icon in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=name, defaults={'icon': icon})


def remove_categories(apps, schema_editor):
    Category = apps.get_model('donations', 'Category')
    Category.objects.filter(name__in=[name for name, _ in DEFAULT_CATEGORIES]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories),
    ]
