# Generated by Django 6.1 on 2026-08-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de réception confirmée'),
        ),
    ]
