# Generated by Django 6.1 on 2026-08-09 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0003_donation_received_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la campagne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Campagne clôturée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('orphanage', models.ForeignKey(limit_choices_to={'role': 'responsable'}, on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL, verbose_name='Orphelinat')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'Campagnes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='need',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='needs', to='donations.campaign', verbose_name='Campagne associée'),
        ),
        migrations.CreateModel(
            name='NeedPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='need_photos/', verbose_name='Photo')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Légende')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='donations.need', verbose_name='Besoin')),
            ],
            options={
                'verbose_name': 'Photo de besoin',
                'verbose_name_plural': 'Photos de besoins',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='NeedFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de suivi')),
                ('donateur', models.ForeignKey(limit_choices_to={'role': 'donateur'}, on_delete=django.db.models.deletion.CASCADE, related_name='followed_needs', to=settings.AUTH_USER_MODEL, verbose_name='Donateur')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='donations.need', verbose_name='Besoin')),
            ],
            options={
                'verbose_name': 'Besoin suivi',
                'verbose_name_plural': 'Besoins suivis',
                'ordering': ['-created_at'],
                'unique_together': {('donateur', 'need')},
            },
        ),
    ]
