# Generated by Django 6.1 on 2026-09-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_campaign_need_campaign_needphoto_needfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='priority_weight',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Très faible'), (2, 'Faible'), (3, 'Normale'), (4, 'Élevée'), (5, 'Critique')], default=3, help_text='Influence le score de priorité des besoins de cette catégorie dans les listes et recommandations aux donateurs.', verbose_name='Niveau de criticité'),
        ),
    ]
